name: Docker

"on":
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "*.*.*"

jobs:
  # https://github.com/edencehealth/workflows
  ares:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@v1
    with:
      container_name: ohdsi-ares
      push_readme: README.md
    secrets: inherit
